# Generated by Django 2.2.6 on 2019-12-21 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_birth', models.CharField(max_length=50)),
                ('Breif_introduction', models.CharField(max_length=500)),
                ('Language', models.CharField(max_length=50)),
                ('Hobbies', models.CharField(max_length=50)),
                ('Website', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_employment', models.CharField(max_length=500)),
                ('About_organization', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skils_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Social_media_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.CharField(max_length=200)),
                ('Twitter', models.CharField(max_length=200)),
                ('Instagram', models.CharField(max_length=200)),
                ('Linkedin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Skills')),
            ],
        ),
    ]
