# Generated by Django 2.2.6 on 2019-12-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_me_experience_percentage_skills_social_media_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Social_media_account',
        ),
        migrations.RenameField(
            model_name='about_me',
            old_name='Breif_introduction',
            new_name='breif_introduction',
        ),
        migrations.RenameField(
            model_name='about_me',
            old_name='Date_of_birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='about_me',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='about_me',
            old_name='Hobbies',
            new_name='hobbies',
        ),
        migrations.RenameField(
            model_name='about_me',
            old_name='Language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='about_me',
            old_name='Website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='About_organization',
            new_name='about_organization',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='Date_of_employment',
            new_name='date_of_employment',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Profession',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='percentage',
            old_name='Percentage',
            new_name='percentage',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='Skils_type',
            new_name='Ability',
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
