# Generated by Django 2.2.6 on 2019-12-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20191227_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentage',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
