# Generated by Django 2.2.6 on 2019-12-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20191227_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='percentage',
            old_name='percentage',
            new_name='rate',
        ),
    ]
