# Generated by Django 2.2.6 on 2019-12-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20191227_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentage',
            name='rate',
            field=models.CharField(max_length=3),
        ),
    ]
